2022-04-05 00:12:22,969 ERROR: Exception on /user/ggtx [GET] [in /home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/mrprogg/flask/microblog1/app/routes.py", line 79, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/mrprogg/flask/microblog1/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mrprogg/flask/microblog1/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/mrprogg/flask/microblog1/app/templates/user.html", line 10, in block 'content'
    {% if user.last_seen %}<p style="font-size: 94%;">Был в сети: {{ moment(user.last_seen).format('LLLL') }}</p>{% endif %}
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'moment' is undefined
2022-04-05 00:14:06,316 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:14:54,502 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:15:18,318 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:16:28,115 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:21:05,819 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:23:26,868 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:25:21,372 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:26:49,813 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:27:57,211 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:29:18,842 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:30:05,897 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 00:30:30,622 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 01:23:48,586 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 01:24:27,444 ERROR: Exception on /index [GET] [in /home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/mrprogg/flask/microblog1/app/routes.py", line 23, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/mrprogg/flask/microblog1/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/mrprogg/flask/microblog1/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/mrprogg/flask/microblog1/app/templates/index.html", line 5, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-04-05 01:28:05,673 INFO: Microblog startup [in /home/mrprogg/flask/microblog1/app/__init__.py:43]
2022-04-05 01:28:08,622 ERROR: Exception on /index [GET] [in /home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/mrprogg/flask/microblog1/app/routes.py", line 23, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/mrprogg/flask/microblog1/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/mrprogg/flask/microblog1/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/mrprogg/flask/microblog1/app/templates/index.html", line 5, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/mrprogg/flask/microblog1/env/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
